Repository WildCodeSchool-2023-09/JS-RemoteFR-SACOD-P2-Oro-Jackson, pull requests merged in 2023-11, with the labels that each got.

#16 Dave
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/main.jsx
  frontend/src/pages/ConfirmPage.jsx
  frontend/src/pages/Contact.jsx
  frontend/src/pages/MakeADrink.jsx
  frontend/src/pages/MostPopular.jsx
  frontend/src/pages/Navbar.css
  frontend/src/pages/Navbar.jsx
  frontend/src/pages/RandomCocktail.jsx
  frontend/src/styles/App.scss
  frontend/src/styles/ConfirmPage.scss
  frontend/src/styles/Contact.scss
  frontend/src/styles/MostPopular.scss
  frontend/src/styles/Navbar.scss
  frontend/yarn.lock
  workflows/deploy-traefik.yml
  workflows/lint.yml
  workflows/remove.yml
Labels: REVIEWED, REVIEW REQUESTED

#18 S02 US3 Make a drink Feature
  frontend/src/pages/MakeADrink.jsx
  frontend/src/pages/MostPopular.jsx
  frontend/src/styles/MakeADrink.scss
  frontend/src/styles/MostPopular.scss
Labels: REVIEWED, REVIEW REQUESTED

#20 Make a drink style and feature update
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/animationEdit.json
  frontend/src/components/Loader.jsx
  frontend/src/pages/MakeADrink.jsx
  frontend/src/pages/RandomCocktail.jsx
  frontend/src/styles/MakeADrink.scss
  frontend/yarn.lock
Labels: REVIEWED

#22 randompage_CSS + Contact & HomePage Responsive
  frontend/src/pages/MakeADrink.jsx
  frontend/src/pages/RandomCocktail.jsx
  frontend/src/styles/App.scss
  frontend/src/styles/Contact.scss
  frontend/src/styles/MostPopular.scss
Labels: REVIEW REQUESTED

#23 Like and share
  frontend/src/assets/share.svg
  frontend/src/components/Like.jsx
  frontend/src/pages/MakeADrink.jsx
  frontend/src/pages/MostPopular.jsx
  frontend/src/styles/Like.scss
  frontend/src/styles/MakeADrink.scss
  frontend/src/styles/MostPopular.scss
  frontend/yarn.lock
Labels: REVIEWED

#25 404page + carousel arrow + style
  frontend/src/App.jsx
  frontend/src/Error-page.jsx
  frontend/src/assets/404animation.json
  frontend/src/assets/arrow.png
  frontend/src/components/Loader.jsx
  frontend/src/pages/MakeADrink.jsx
  frontend/src/pages/MostPopular.jsx
  frontend/src/styles/Error.scss
  frontend/src/styles/MakeADrink.scss
Labels: REVIEW REQUESTED

#27 Fix de bug 404 et random cocktails
  frontend/src/pages/MostPopular.jsx
  frontend/src/pages/RandomCocktail.jsx
Labels: REVIEWED

#28 Navbar menu burger + responsive
  frontend/src/pages/Navbar.jsx
  frontend/src/styles/Navbar.scss
Labels: REVIEWED

#30 Last updates
  frontend/src/pages/RandomCocktail.jsx
Labels: REVIEWED
